receivers:
  - id: 1
    kind: dummy
    properties:
      errorInterval: 10s
      shutdownDuration: 0s
  - id: 2
    kind: HTTP
    properties:
      listenAddress: :8080
senders: 
  - id: 1
    kind: dummy
    properties:
      errorInterval: 0s
      shutdownDuration: 10s
  - id: 1
    kind: webPush
    properties:
      listenAddress: :8091
      repositoryType: InMemory
